# Generated by Django 3.0.2 on 2020-01-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authon',
            new_name='author',
        ),
    ]
